### ISSUE TITLE
Regenerate docker image on top of latest upstream

### ISSUE THREAD

**Issue by mboes** [tweag/HaskellR#203]
The haskellr docker image builds on top of the stock images provided by the stack project. They recently changed the entrypoint (see #202) so that entering the image is more efficient than it previously was. We should regenerate our docker image on top.

@borsboom I foresee the docker registry caching getting in the way. Do the new images with the fixed entrypoints have a different tag associated to them?

**Comment by borsboom** [comment]
@mboes Every image we upload to the fpco repos gets its own unique tag.  Note that only the LTS-3 images have the new entrypoint.

**Comment by mboes** [comment]
Fixed by #218.
