### ISSUE TITLE
"The pkg-config package 'libR' version >=3.0 is required but it could not be found."

### ISSUE THREAD

**Issue by michaelochurch** [tweag/HaskellR#206]
I'm working through the build/install directions given [here](http://tweag.github.io/HaskellR/docs/build-and-install.html). When I tried to build ```H``` (command was: ```stack build --copy-bins H```) I ended up getting the error message above.

It seems that ```inline-r-0.7.0.0``` depends on ```libR >=3.0```, so I feel like I'm missing a step. How do I ensure that Stack has access to ```libR``` when I build ```H```?

Thanks for doing this. I'm really excited to start using Haskell for data science.

**Comment by Fuuzetsu** [comment]
Did you see https://github.com/tweag/HaskellR/issues/200 ? This issue looks like a duplicate.

**Comment by michaelochurch** [comment]
It does look like a duplicate. Unfortunately, the takeaway seems to be that no one has solved this for OS X. How exactly do I use ```pkg-config``` to locate my ```libR```? I tried ```pkg-config --libs libR``` and it found nothing (but I've never used ```pkg-config``` before...)

Does having ```R``` mean that I have ```libR``` or is that something separate?

**Comment by Fuuzetsu** [comment]
It all depends how you got R, how it's packaged &c. The answer as on #200 is that we don't really know because none of us use OSX. Anyway I will close as duplicate, please put further comments on #200
