### ISSUE TITLE
`stack --docker build` requires `stack docker pull`, which fails. 

### ISSUE THREAD

**Issue by michaelochurch** [tweag/HaskellR#207]
I'm trying out the "From Github" approach to H installation, detailed [here](http://tweag.github.io/HaskellR/docs/build-and-install.html). 

Here's a reproduction of the problem, at command-line, on my system (OS X, GHC 7.10.2).

```
$ stack --docker build
The Docker image referenced by stack.yaml has not
been downloaded:
    tweag/haskellr:latest

Run 'stack docker pull' to download it, then try again.
$ stack docker pull
Pulling image from registry: 'tweag/haskellr:latest'
FATA[0000] Post http:///var/run/docker.sock/v1.18/images/create?fromImage=tweag%2Fhaskellr%3Alatest: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
Could not pull Docker image:
    tweag/haskellr:latest
There may not be an image on the registry for your resolver's LTS version in
stack.yaml.
```

**Comment by borsboom** [comment]
Copying from https://github.com/commercialhaskell/stack/issues/999:

> Stack's Docker support requires the Docker client and the Docker Engine to be running on the same host. That effectively means it only works on Linux 64-bit, since that's the only platform Docker Engine runs on. See https://github.com/commercialhaskell/stack/wiki/Docker#prerequisites for more information about the prerequisites for stack --docker. https://github.com/commercialhaskell/stack/issues/194 is tracking adding support for non-Linux platforms.

Can you update HaskellR's build instructions to include a link to https://github.com/commercialhaskell/stack/wiki/Docker?  This question has come up several times now from people trying to build it using Docker on unsupported platforms.

**Comment by michaelochurch** [comment]
I'd also like to have a relatively easy way to use Stack's docker support *and* HaskellR on a Mac. 

I'm working with a team of people who'd love to use Haskell, but they need R for their daily work and they develop on Macs. So, to me personally, this is an important target. I doubt that I'm alone on that.

Even if I can personally figure out (I'm sure I can) how to , I'm not at the point where I can ask data scientists on Macs (some of whom are fresh out of PhD programs and, while they can code, don't identify as programmers) to install HaskellR. I'd love to get things to that state, because they aren't averse to learning Haskell, but the ability to use R on a daily basis is non-negotiable for them.

**Comment by Fuuzetsu** [comment]
@michaelochurch the docker part of HaskellR's build process is only there to ease getting ihaskell running. It is not obligatory by any means. On the wiki page perhaps we should make that explicit. If you have a working ihaskell setup on your machine, you do not need the docker stuff.

Of course we want  to make it easy for people to use HaskellR. As far as OSX goes is that noone on the HaskellR team currently has readily available access to OSX machine so what support we can offer *right this second* is very limited. Until we can find OSX machine for us to use or find someone else who can step up and handle this part, we can't do much more. It is not by choice that we can't provide extensive support for OSX right now. Hopefully that will change in near future.

**Comment by michaelochurch** [comment]
This makes a lot of sense. Thanks.

If resources are a problem (since you mentioned not having an OS X machine
on hand) have you thought about soliciting clients or donations? Haskell is
still a niche language where I am (Chicago) but the do-it-right culture of
functional programming is catching on quickly, and the whole world seems to
use R because in spite of it being a crappy language, it has excellent data
analysis and machine learning tools.

If you want me to look around for possible clients, I can. I don't want to
promise anything, but I feel like there must be a lot of latent demand for
what you are dong.

**Comment by Fuuzetsu** [comment]
I am but a mere employee so I can't answer such questions. @mboes can though I don't know when he'll be available this week.

**Comment by mboes** [comment]
@michaelochurch increasing contributions sounds great. Hit me up with an email at m@tweag.io and let's figure out how to make it happen.

In the meantime, if any OS X users out there feel like tackling #200, that would be a great way to dip your toes into contributing to HaskellR.
