### ISSUE TITLE
Test suite run failure on Stackage

### ISSUE THREAD

**Issue by snoyberg** [tweag/HaskellR#208]
https://gist.github.com/anonymous/7b5f3bfa6aa497573dc2

**Comment by Fuuzetsu** [comment]
@snoyberg is there any info about how these tests are ran? `cabal test`?

**Comment by snoyberg** [comment]
Yes, it's run via cabal test.

**Comment by Fuuzetsu** [comment]
I was unable to reproduce this yesterday. A simple

```
cabal configure --enable-tests && cabal build && cabal test
```

worked for me. Is there anything we can do to dig into this further?

**Comment by snoyberg** [comment]
Sorry, nothing else comes to mind.

On Tue, Sep 22, 2015 at 7:45 PM, Mateusz Kowalczyk <notifications@github.com

**Comment by mboes** [comment]
Closing, since HaskellR out of Stackage temporarily.
