### ISSUE TITLE
Problem with sample code on OS X 10.9.5

### ISSUE THREAD

**Issue by kryoxide** [tweag/HaskellR#209]
So i'm having a problem with your [sample code](http://tweag.github.io/HaskellR/docs/differences-repl-source.html). After some minor changes I got it to compile but now I'm getting the following error:

```Error: C stack usage  140730332267004 is too close to the limit```

The code is short enough:

```haskell
{-# LANGUAGE QuasiQuotes #-}
module Main where

import qualified H.Prelude as H
import Language.R.QQ

import Lib

hello :: String -> H.R s ()
hello name = do
    [r| print(s_hs) |]
    return ()
  where
    s = "Hello, " ++ name ++ "!"

main :: IO ()
main = do
  putStrLn "Name ?"
  name <- getLine

  H.withEmbeddedR H.defaultConfig $ H.runRegion (hello name)
```

My R Version is ```R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"```

I installed HaskellR using stack as outlined [here](http://tweag.github.io/HaskellR/docs/build-and-install.html)

**Comment by kryoxide** [comment]
Also my ghc-version is 7.10.2
My stack version is 0.1.3.1, Git revision 908b04205e6f436d4a5f420b1c6c646ed2b804d7

**Comment by qnikst** [comment]
Thanks for a report. It seems that it's the result of R's stack protection, that doesn't play well with ghc segmented stack. Currently we have a workaround for this issue [1] )that works for us on linux systems, and worked before on OS X), but according to your report it doesn't work for you now. We will take a look into this issue on a MacOS soon.

Meanwhile you could try to set limit by hand:

launchctl limit stack 67104768
ulimit -s 65532

Please report if this workaround will work for you.

[1] https://github.com/tweag/HaskellR/blob/master/inline-r/src/Language/R/Instance.hs#L205-L226

**Comment by kryoxide** [comment]
Doesn't seem to work for me, I ran exactly the two commands you specified before running the program with ```stack runghc```.

**Comment by qnikst** [comment]
Thanks for testing that. One more question, just to be precise, are you compiling program or run it in interpreter?

**Comment by kryoxide** [comment]
I'm compiling it, thanks for taking a look at my report.

**Comment by kryoxide** [comment]
Hmm the problem only seems to occur when I run the program with ```stack runghc app/Main.hs```. 
When I build the project  with ```stack build``` and then run the resulting binary it strangely works. I'm not sure why ```stack runghc app/Main.hs``` doesn't work...

**Comment by qnikst** [comment]
Thanks for investigation, this narrow a problem a lot. I'm not sure that I know what is the difference between `stack runghc` and normal execution, but this makes easier to find out a solution.

P.S. I'm using following workflow when working on small projects with H, maybe it could work for you as a workaround. I'm building H/inline-r with `stack build` and then do `stack exec zsh` , then inside a shell I can use cabal and normally work in provisioned environment.

**Comment by mboes** [comment]
I suspect `runghc` uses GHCi under the hood, or at any rate bytecode interpretation. If it uses GHCi, the stack check could be thwarted by the fact that GHCi does not run code in the main thread, unless you pass `-fno-ghci-sandbox`, which H does activate.

@kryoxide could you tell us if you get the same error with the following command?

```
$ echo -e 'main\nJoe' | stack exec -- ghci -fno-ghci-sandbox /tmp/foo.hs
```

where `/tmp/foo.hs` contains your sample program? What about without `-fno-ghci-sandbox`?

**Comment by kryoxide** [comment]
@mboes I don't get an error when using your command. When omitting ```-fno-ghci-sandbox``` it occurrs again, same as if i use ```stack runghc``` (minus the ghci prompt of course).

**Comment by mboes** [comment]
aha! So there you have it - the culprit is the GHCi sandboxing, at any rate on OS X. We may need an FAQ to cover these kinds of issues. @Fuuzetsu could you start one (in a separate ticket, close this one)?

**Comment by mboes** [comment]
Followup ticket here: #211
