### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by mboes** [tweag/HaskellR#211]
Covering common issues such as in #209.

**Comment by kryoxide** [comment]
I'm not sure if this is the right place to ask this, but is it intentional that [inline-r](http://hackage.haskell.org/package/inline-r) doesn't have hackage documentation? For my personal development workflow it would be really helpful to have it.

**Comment by Fuuzetsu** [comment]
It's because Hackage doesn't have the necessary things to build inline-r and therefore the docs:
http://hackage.haskell.org/package/inline-r-0.7.1.0/reports/3

**Comment by mboes** [comment]
Certainly isn't. ;) I wish Hackage did have documentation, but the dependency on R is currently thwarting the build. Fortunately stackage.org builds the documentation just fine: https://www.stackage.org/nightly-2015-10-01/package/inline-r-0.7.1.0.

**Comment by kryoxide** [comment]
Also this [sample code](http://tweag.github.io/HaskellR/docs/differences-repl-source.html) doesn't seem to compile because of this line: 
```haskell
R.withEmbeddedR R.defaultConfig (hello name)
```
 where ```hello :: String -> R s () ``` but the second argument to ```R.withEmbeddedR``` should be ```IO ()```. If you tell me how to fix this I could do this myself.

**Comment by mboes** [comment]
@kryoxide fixed. The documentation on the website was consistent with the development branch, but not the hackage release version. Tricky to document both at the same time. Might need to fork the documentation. Notice that this very code example compiled just fine a few days ago when you reported #209.

**Comment by mboes** [comment]
BTW, best to report these as separate issues.

**Comment by mboes** [comment]
Done. See here: http://tweag.github.io/HaskellR/docs/faq.html.
