### ISSUE TITLE
-fPIC failure using LTS>=3.0 Docker images

### ISSUE THREAD

**Issue by mboes** [tweag/HaskellR#213]
As originally reported by @ooblahman in #212:

```
2015-10-11 20:32:05.536469: [warn] /usr/bin/ld: .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Lib.dyn_o: relocation R_X86_64_PC32 against symbol `testzu2kZZ0y1f3EcZZLZZNPKvquIVd_Lib_someFunc7_closure' can not be used when making a shared object; recompile with -fPIC @(stack_Bp003b8iWaELtdr693pSPs:Stack.Build.Execute src/Stack/Build/Execute.hs:1241:35)
2015-10-11 20:32:05.536677: [warn] /usr/bin/ld: final link failed: Bad value @(stack_Bp003b8iWaELtdr693pSPs:Stack.Build.Execute src/Stack/Build/Execute.hs:1241:35)
2015-10-11 20:32:05.53678: [warn] collect2: error: ld returned 1 exit status @(stack_Bp003b8iWaELtdr693pSPs:Stack.Build.Execute src/Stack/Build/Execute.hs:1241:35)

--  While building package test-0.1.0.0 using:
      /home/anand/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ build lib:test exe:test-exe --ghc-options  -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
```

And later

> It appears building on docker images with stackage > lts-2.14 reproduces the issue. (e.g. building on a docker image identical to tweag/haskellr:latest except with lts-3.7).

**Comment by YPares** [comment]
Ok, so the bug doesn't reproduce with either lts-3.7 or 3.9 with the following stack config:
```yml
resolver: lts-3.9
packages:
    - '.'
extra-deps: 
    - inline-r-0.7.1.2
flags: {}
docker:
    enable: true
    repo: tweag/haskellr:latest
```
`stack build` compiles the 'test' gist alright
and `stack exec test-exe` works.

**Comment by YPares** [comment]
@ooblahman Hi, I can't reproduce your bug here. Are you sure you've been using the docker image all along? Because I do get the same kind of errors without docker enabled.

**Comment by ooblahman** [comment]
Oh it's not the resolver in the YAML that causes the error -- it's the LTS version off of which the docker image itself is based. i.e. running on a docker created by this image fails for me: 
```
FROM fpco/stack-build:lts-3.7
MAINTAINER Mathieu Boespflug <m@tweag.io>

# Install system dependencies.
RUN apt-add-repository ppa:marutter/rrutter \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
         libzmq3-dev \
         python-dev \
         python-pip \
         r-base \
         r-base-dev \
    && rm -rf /var/lib/apt/lists/*

# Pin version for repeatability.
RUN pip install 'ipython[all]==3.2.1'
```

**Comment by borsboom** [comment]
This doesn't seem to be related to usage of Docker.  I was just able to reproduce this on a fresh Ubuntu 14.04 VM without using Stack's Docker integration.  I installed R using the same commands as the Dockerfile above, and also reproduced when R was installed using:

```
echo 'deb http://cran.rstudio.com/bin/linux/ubuntu trusty/' >>/etc/apt/sources.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
apt-get update
apt-get install --no-install-recommends r-base r-base-dev r-recommended
```

**Comment by borsboom** [comment]
Looks like the problem is the linker.  On my plain Ubuntu 14.04 VM, switching the linker to `ld.gold` (GNU gold) fixed the build.  The lts-2 Docker images use `ld.gold` (GNU gold), while the lts-3 images use Ubuntu 14.04's default `ld.bfd` (GNU ld), so that also explains why switching images causes this problem.  I'll push a new lts-3 image with that uses `ld.gold` soon.

**Comment by borsboom** [comment]
I've pushed a new lts-3.13 image that uses ld.gold: `fpco/stack-build:lts-3.13_20151112`

**Comment by mboes** [comment]
For posterity, looks like the ld.bfd bug we got hit by was https://sourceware.org/bugzilla/show_bug.cgi?id=17689. Some distros patch ld.bfd. Perhaps newer releases also have this issue fixed. The safest bet here is to switch to the gold linker, as @borsboom suggests.

I've added a FAQ entry regarding this issue: http://tweag.github.io/HaskellR/docs/faq.html.

@ooblahman confirm and close?
