### ISSUE TITLE
Failure to build on OS X El Capitan, GHC 7.10.2

### ISSUE THREAD

**Issue by tranma** [tweag/HaskellR#223]
I tried to build H with the above setup and got this.

```
    Configuring inline-r-0.7.0.0...
    Building inline-r-0.7.0.0...
    Preprocessing library inline-r-0.7.0.0...
    c2hs: C header contains errors:

    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/stdlib.h:177: (column 47) [ERROR]  >>> Syntax error !
      The symbol `__WATCHOS_PROHIBITED' does not fit here.
```

Looks like a similar issue to this cuda issue: https://github.com/tmcdonell/cuda/issues/33
Maybe the cbits needs some fiddling, see: https://github.com/haskell/c2hs/issues/85

**Comment by tranma** [comment]
Oops, never mind. The Hackage version is just different to master. I'll just use master.

Sorry for the trouble.

**Comment by mboes** [comment]
Indeed - a maintenance release with El Capitan support is long overdue. I'll see if I can push that out the door later today.
