### ISSUE TITLE
Bad interaction with SIGPIPE for failed network sends

### ISSUE THREAD

**Issue by snoyberg** [tweag/HaskellR#224]
@bitonic and I just debugged an issue where two processes were communicating over a socket. The Haskell code has built-in logic to detect that the socket has been interrupted and recover (when either the `send` call throws an exception, or `recv` returns an empty `ByteString`). However, this situation resulted in the R runtime receiving the SIGPIPE generated by the failed `send` call and shutting down.

One workaround we discovered was modifying the `send` system call to set the `MSG_NOSIGNAL` flag, which solves the problem, but (1) only works on Linux, and (2) requires either an invasive change to the network package or locally modified FFI calls.

**Comment by mboes** [comment]
Likely R is installing its own signal handlers. Not sure whether we can disable that. Will investigate.

**Comment by Fuuzetsu** [comment]
@snoyberg do you have any small snippet on hand that we could use to quickly replicate and then test against?

**Comment by snoyberg** [comment]
Unfortunately I don't, this was part of a much larger application.

**Comment by Fuuzetsu** [comment]
Please see the minor commit above and check if it fixes your problem.

**Comment by bitonic** [comment]
I can confirm that that commit fixes our problem, thanks!
