### ISSUE TITLE
cabal install with Revolution R fails

### ISSUE THREAD

**Issue by alexvorobiev** [tweag/HaskellR#240]
We use Revolution R Enterprise and for some reason cabal does not see it: 

$ cabal install --extra-include-dirs="/usr/lib64/Revo-7.4/R-3.1.3/lib64/R/include" --extra-lib-dirs="/usr/lib64/Revo-7.4/R-3.1.3/lib64/R/lib" H
Resolving dependencies...
Configuring inline-r-0.8.0.1...
Failed to install inline-r-0.8.0.1
Build log ( /home/user/.cabal/logs/inline-r-0.8.0.1.log ):
Configuring inline-r-0.8.0.1...
setup-Simple-Cabal-1.22.5.0-x86_64-linux-ghc-7.10.3: Missing dependency on a
foreign library:
* Missing C library: R
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
cabal: Error: some packages failed to install:
H-0.8.0.0 depends on inline-r-0.8.0.1 which failed to install.
inline-r-0.8.0.1 failed during the configure step. The exception was:
ExitFailure 1

**Comment by mboes** [comment]
Not sure what's going on here. Have you checked that libR.so exists in /usr/lib64/Revo-7.4/R-3.1.3/lib64/R/lib? Could you provide the output of passing `--verbose` also to the `cabal` command?

It works with Microsoft R Open 3.2.3 (Revolution R's new name).

**Comment by mboes** [comment]
Actually... `--verbose=3`.

**Comment by alexvorobiev** [comment]
The `--verbose=3` revealed that a few shared libraries were not visible so as a temporary solution I created corresponding symlinks and modified `LD_LIBRARY_PATH`. After that H was built and installed to my `~/.cabal/bin`. 

We also have Nix but I wasn't able to use `stack --nix` because it wanted to install R from the Nix repository. Is there any way to modify `stack.yaml` so that Nix would take care of all the dependencies but still use the Revolution R instead of its own R?

**Comment by mboes** [comment]
It should be possible to modify the shell.nix to point to your R installation rather than install its own R. You can say `stack --nix --nix-shell-file=someshellfile.nix` on the command line and it will use that file for creating the nix shell. The following untested shell file  might do the trick:

```
with (import <nixpkgs> { });
with stdenv.lib;

haskell.lib.buildStackProject {
  name = "HaskellR";
  buildInputs = [ ncurses pkgconfig python34Packages.ipython zeromq zlib ];
  extraArgs = ["--extra-lib-dirs=/path/to/RevolutionR/lib" "--extra-include-dirs=/path/to/RevolutionR/include"];
  LANG = "en_US.UTF-8";
  # Might additionally need to set LD_LIBRARY_PATH
  LD_LIBRARY_PATH="...";
}
```

Make  sure to use a recent checkout of Nixpkgs - `buildStackProject` was only added recently (in the last couple of months or so). See the existing `shell.nix` in the HaskellR repository for a starting point.
