### ISSUE TITLE
Promise's value is not necessary a PairList

### ISSUE THREAD

**Issue by sorawee** [tweag/HaskellR#241]
https://github.com/tweag/HaskellR/blob/master/inline-r/src/Language/R/HExp.chs#L133 indicates that `a` is a `PairList`. However, it actually could be any R value.

**Comment by qnikst** [comment]
Thanks, you are right, and `b` should be expression there, right?

**Comment by sorawee** [comment]
I think that `b` could be any R expression (no constraint).

Does this mean that `R.IsPairList` doesn't work, and that this library is type-unsound?

**Comment by qnikst** [comment]
I think - yes, and the type should be fixed in next version, though I'd like to verify that, will update this ticket ASAP.

**Comment by mboes** [comment]
Should be fixed in https://github.com/tweag/HaskellR/commit/60540f6ccf00d3bcc263bca31fc9958a01fca784. No idea why the constraints were so wrong to begin with. @sorawee confirm?

Inspecting promises is a bit unusual. What's your use case? Better yet - do you have a regression test we could add to the test suite?

**Comment by sorawee** [comment]
I don't think that changing `b` to `R.Expr` is correct. For example, I found that it could be `R.Lang` (sorry for the confusion, when I said R expression in the above comment, I meant any SEXP)

We are trying to write a parser that turns R source code to our own ADT. Indeed, we have no need to inspect the Promise value at all, but we want to do it anyway for completeness. Basically, we just copy the `toJSON` function (https://github.com/tweag/HaskellR/blob/master/inline-r/src/Language/R/Debug.hs#L61) and change it to fit our need.

Here's some example:

    Input: `print`
    Output:
    Expr 0
      [Symbol
         (RSymbol (Just "print")
            (Just
               (Promise (Symbol (RSymbol Nothing Nothing Nil))
                  (Lang
                     (RLang
                        (Left (RSymbol (Just "lazyLoadDBfetch") (Just (Builtin 651)) Nil))
                        [(Int [500175, 107], Nothing),
                         (Symbol
                            (RSymbol (Just "datafile")
                               (Just (Symbol (RSymbol Nothing Nothing Nil)))
                               Nil),
                          Nothing),
                         (Symbol
                            (RSymbol (Just "compressed")
                               (Just (Symbol (RSymbol Nothing Nothing Nil)))
                               Nil),
                          Nothing),
                         (Symbol
                            (RSymbol (Just "envhook")
                               (Just (Symbol (RSymbol Nothing Nothing Nil)))
                               Nil),
                          Nothing)]))
                  (Just
                     (REnv
                        [(Nil, Just (RSymbol (Just "this") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "expr") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "envhook") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "envenv") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "i") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "compressed") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "rvars") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "vars") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "map") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "env") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "datafile") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "mapfile") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "mkenv") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "environment") Nothing (Builtin 484))),
                         (Nil, Just (RSymbol (Just "set") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "getFromFrame") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "existsInFrame") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "parent.env<-") Nothing (Builtin 510))),
                         (Nil, Just (RSymbol (Just "readRDS") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "glue") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "filebase") Nothing Nil)),
                         (Nil, Just (RSymbol (Just "envir") Nothing Nil))]
                        (Just
                           (REnv
                              [(Nil, Just (RSymbol (Just "basedb") Nothing Nil)),
                               (Nil, Just (RSymbol (Just "glue") Nothing Nil)),
                               (Nil, Just (RSymbol (Just "existsInBase") Nothing Nil)),
                               (Nil, Just (RSymbol (Just "..lazyLoad") Nothing Nil))]
                              (Just (REnv [] (Just (REnv [] Nothing Nothing)) Nothing))
                              Nothing))
                        Nothing))))
            Nil)]

As you can see, the "expression" part of a Promise could be `R.Lang`

(Note: the output is not entirely correct. We have to put `Nothing` and `Nil` in some part to avoid infinite loop when inspecting a cyclic structure).

**Comment by mboes** [comment]
Neat project.

Hm, so the [Documentation](https://cran.r-project.org/doc/manuals/r-release/R-ints.html#The-_0027data_0027) does indeed say that when the documentation says "expression", it doesn't just mean EXPRSXP. It really means either EXPRSXP, LANGSXP or SYMSXP. So I introduced a `IsExpression` predicate to capture that once and for all and generalized the types of `Lang` and `Promise` accordingly. Does that fit your observations?

**Comment by mboes** [comment]
In commit afe03b84ec324ce5680b170bc0b8e693e6004e79 I meant to add...

**Comment by mboes** [comment]
Closing. Please reopen if this is still a problem.
