### ISSUE TITLE
Some weird issues with Symbol

### ISSUE THREAD

**Issue by sorawee** [tweag/HaskellR#242]
Given `H.Symbol pname val internal`, I would expect ` H.hexp pname` to be `(H.Char ...)`. However, this might not be true. I encounter a case where `castPtr (R.unSEXP nilValue) == R.unSEXP pname`. Not exactly sure how this happens (it happens when I inspect the promise value under the builtin `print`)

Another issue is that, for unbound identifier (symbol), `val` seems to be an address linking to itself. According to https://cran.r-project.org/doc/manuals/r-release/R-ints.html, this should be `R_UnboundValue` instead.

**Comment by qnikst** [comment]
According to latter part, in argument lists uses self link to indicate end of the list. This was a surprising fact for us but this is how R works.

With regard to a former I'm not sure what is happening, can you give some examples that puzzled you, I can try to test that and will be able to tell something reasonable about that.

**Comment by sorawee** [comment]
I think I know the issue now. Let `sexp` be a `SEXP s 'R.Symbol`. `sexp` doesn't necessary has three fields if it's a special value `unboundValue`. Calling `H.hexp sexp` will give back an unsafe `H.HExp s 'R.Symbol` because if we inspect the first field and perform some operation, thinking that it's definitely a `SEXP s 'R.Char`, then segmentation fault could happen.

Sorry if I say something confusing. I just started learning Haskell (and also R)!

**Comment by mboes** [comment]
Sounds reasonable. Could you submit a PR loosening the type of `R.Symbol` according to what you observe?
