### ISSUE TITLE
claim about parsing during runtime

### ISSUE THREAD

**Issue by aavogt** [tweag/HaskellR#248]
http://tweag.github.io/HaskellR/docs/implementation-of-quasiquoters.html says "Therefore, a quasiquote expands to Haskell code that builds an equivalent AST at runtime, using the view and inverse view function defined above."

But if I compile with -ddump-splices, I see that the quasiquote generates haskell code which includes a string literal containing the R code and a call to `Language.R.QQ.parse`

    Asybench.hs:(41,39)-(46,6): Splicing expression
        "\n\
        \     {\n\
        \      m <- scm::scam(ts ~ s(ns, bs='mpi'),\n\
        \              data=data.frame(ts=ts_hs, ns=ns_hs)) \n\
        \      predict(m, newdata=data.frame(ts=tNew_hs))}\n\
        \    "
      ======>
        (H.eval
         =<<
           (\ x_a9Da x_a9Db x_a9Dc
              -> do { let sx_a9Dd
                            = (GHC.IO.unsafePerformIO
                               $ (do { exprs_a9De <- Language.R.QQ.parse
                                                       "function(ns_hs,ts_hs,tNew_hs){\n\
                                                       \     {\n\
                                                       \      m <- scm::scam(ts ~ s(ns, bs='mpi'),\n\
                                                       \              data=data.frame(ts=ts_hs, ns=ns_hs)) \n\
                                                       \      predict(m, newdata=data.frame(ts=tNew_hs))}\n\
                                                       \    }";
                                       SomeSEXP e_a9Df <- R.indexVector exprs_a9De 0;
                                       clos_a9Dg <- R.eval e_a9Df (R.release H.globalEnv);
                                       unSomeSEXP clos_a9Dg R.preserveObject;
                                       return clos_a9Dg }));
                      (H.io
                       $ (case sx_a9Dd of {
                            SomeSEXP f_a9Dh
                              -> ((R.lcons f_a9Dh)
                                  =<<
                                    ((R.withProtected
                                        ((R.withProtected
                                            ((R.withProtected (return (R.release H.nilValue)))
                                             $ (\ cdr_a9Di
                                                  -> do { car_a9Dj <- H.mkSEXPIO x_a9Dc;
                                                          R.lcons car_a9Dj cdr_a9Di })))
                                         $ (\ cdr_a9Dk
                                              -> do { car_a9Dl <- H.mkSEXPIO x_a9Db;
                                                      R.lcons car_a9Dl cdr_a9Dk })))
                                     $ (\ cdr_a9Dm
                                          -> do { car_a9Dn <- H.mkSEXPIO x_a9Da;
                                                  R.lcons car_a9Dn cdr_a9Dm }))) })) }
              ns ts tNew))

**Comment by mboes** [comment]
FIxed in 6c8156c3d3f7762b7709ba750114991251f71678. That documentation section was outdated: only inline-r releases prior to 0.8 (the latest release) behaved that way.
