### ISSUE TITLE
can't load .so/.DLL when building H

### ISSUE THREAD

**Issue by goodcucumber** [tweag/HaskellR#252]
I've tried `stack build`,`runhaskell build`,they all told me 
`<command line>: can't load .so/.DLL for: D:\dev\R\bin\x64\R.dll (addDLL: could not load DLL)`
Do any one knows how to build it?(I'm using windows 10 x64)

**Comment by facundominguez** [comment]
Hello @goodcucumber. Please, could you share the output of `ghc --info`?

**Comment by goodcucumber** [comment]
@facundominguez ok


 ghc --info

 [("Project name","The Glorious Glasgow Haskell Compilation System")
 ,("GCC extra via C opts"," -fwrapv")
 ,("C compiler command","$topdir/../mingw/bin/gcc.exe")
 ,("C compiler flags"," -fno-stack-protector")
 ,("C compiler link flags","")
 ,("Haskell CPP command","$topdir/../mingw/bin/gcc.exe")
 ,("Haskell CPP flags","-E -undef -traditional ")
 ,("ld command","$topdir/../mingw/bin/ld.exe")
 ,("ld flags","")
 ,("ld supports compact unwind","YES")
 ,("ld supports build-id","YES")
 ,("ld supports filelist","NO")
 ,("ld is GNU ld","YES")
 ,("ar command","$topdir/../mingw/bin/ar.exe")
 ,("ar flags","q")
 ,("ar supports at file","YES")
 ,("touch command","$topdir/touchy.exe")
 ,("dllwrap command","$topdir/../mingw/bin/dllwrap.exe")
 ,("windres command","$topdir/../mingw/bin/windres.exe")
 ,("libtool command","")
 ,("readelf command","")
 ,("perl command","$topdir/../perl/perl.exe")
 ,("cross compiling","NO")
 ,("target os","OSMinGW32")
 ,("target arch","ArchX86_64")
 ,("target word size","8")
 ,("target has GNU nonexec stack","False")
 ,("target has .ident directive","True")
 ,("target has subsections via symbols","False")
 ,("Unregisterised","NO")
 ,("LLVM llc command","llc")
 ,("LLVM opt command","opt")
 ,("Project version","7.10.3")
 ,("Project Git commit id","97e7c293abbde5223d2bf0516f8969bdd1a9a7a2")
 ,("Booter version","7.10.2")
 ,("Stage","2")
 ,("Build platform","x86_64-unknown-mingw32")
 ,("Host platform","x86_64-unknown-mingw32")
 ,("Target platform","x86_64-unknown-mingw32")
 ,("Have interpreter","YES")
 ,("Object splitting supported","YES")
 ,("Have native code generator","YES")
 ,("Support SMP","YES")
 ,("Tables next to code","YES")
 ,("RTS ways","l debug thr thr_debug thr_l thr_p ")
 ,("Support dynamic-too","NO")
 ,("Support parallel --make","YES")
 ,("Support reexported-modules","YES")
 ,("Support thinning and renaming package flags","YES")
 ,("Uses package keys","YES")
 ,("Dynamic by default","NO")
 ,("GHC Dynamic","NO")
 ,("Leading underscore","NO")
 ,("Debug on","False")
 ,("LibDir","D:\\dev\\Haskell\\7.10.3\\lib")
 ,("Global Package DB","D:\\dev\\Haskell\\7.10.3\\lib\\package.conf.d")
 ]

**Comment by mboes** [comment]
@goodcucumber We don't support Win64 yet, and 32-bit support needs PR #251 to pass the tests properly, to work around a c2hs bug. Would it be problematic to use 32-bits for now? We can create a followup ticket about 64-bit support.

**Comment by goodcucumber** [comment]
So it's impossible to run HaskellR on a 64bit windows?

**Comment by mboes** [comment]
Not saying it's impossible - just that it's not currently supported. So I don't know how well it works. If you're willing to help out with windows 64 support that would be great. :)

**Comment by goodcucumber** [comment]
OK, I get it. I want to help but I'm just a beginner at Haskell, I don't know how it works... :(
Though not able to try HaskellR now, I love this project!
