### ISSUE TITLE
How to get a list as a SEXP type ?

### ISSUE THREAD

**Issue by stla** [tweag/HaskellR#256]
Hello,
I am still a newbie in Haskell and I am not an eminent English speaker. The technical machinery behind my question is far beyond my skills, so please excuse me for my vocabulary.
In [this blog post](http://stla.github.io/stlapblog/posts/FloatExpansionHaskell.html) I give an example of a function returning a list of integers and I turn it into a function compatible with R (section "Second dynamic linker" of the blog post). This is done with the following line of code, where `DV` is the `Data.Vector.SEXP` module:
`poke result $ DV.toSEXP $ DV.fromList myintegerlist`
where `myintegerlist` is for example `[1, 0, 1]`. 
Then the type of `result` defined by this line is `Ptr (SEXP s R.Int)`. 
When I call the function in R, I get the vector `c(1, 0, 1)`. Very nice.
Now, I am wondering how I could get a list in R. Assume for example my Haskell code generates the list `[[0,0], [1,1]]`. How can I turn this list in `SEXP` type ? I would like to get `list(c(0,0), c(1,1))` in R.  I have done many attempts with `Ptr (SEXP s R.List)`, but unsuccesful. 
I hope my question is clear...

**Comment by stla** [comment]
I've found a solution...

**Comment by GregorySchwartz** [comment]
What was the solution?

**Comment by stla** [comment]
@GregorySchwartz  `peekArray` - see [here](https://groups.google.com/forum/#!topic/haskellr/6M0Ar1DfJJQ).
But you need to know the length of the list in advance.
