### ISSUE TITLE
 C stack usage problem with Jupyter/IHaskell on mac

### ISSUE THREAD

**Issue by JulianZhang** [tweag/HaskellR#262]
I install HaskellR as flowing guide

http://tweag.github.io/HaskellR/docs/build-and-install.html

But if I run any R command such as [r|1+1|], the will be an error as "C stack usage xxx is too close to the limit".

I think the error is same as blow, But I didn't know how to fix it on Ihaskell case

https://github.com/tweag/HaskellR/issues/209

**Comment by mboes** [comment]
Could you tell us more about your platform? OS X? Linux? Windows?

**Comment by JulianZhang** [comment]
Hi, my platform is OS X.

**Comment by JulianZhang** [comment]
Hi mboes, I think the problem is the same with http://tweag.github.io/HaskellR/docs/faq.html

But I didn't know how to pass the -fno-ghci-sandbox to notebook

**Comment by mboes** [comment]
This may well be an upstream feature request for the IHaskell project: be able to pass arbitrary GHC options to the Jupyter haskell kernel. I don't know if that's possible. If it is then would love to have an augmented FAQ entry regarding this. :)

**Comment by mboes** [comment]
Does typing `:set -fno-ghci-sandbox` in the first cell in a notebook work? I'm not sure that it would, since it's possible that this option only works if it's set *before* launching GHCi, rather than within a session.

**Comment by JulianZhang** [comment]
Yes, it works, thank you. And I will raise a question on IHASKELL, to find a way to change the system setting.

**Comment by JulianZhang** [comment]
Hi mboes, maybe you can add it to FAQ, if want fix it by default, just add ":set -fno-ghci-sandbox" to ~/ihaskell/rc.hs (create it if didn't exist)

**Comment by mboes** [comment]
Sounds great. Could you push a PR with that fix? Many thanks. :)

**Comment by JulianZhang** [comment]
Hi mboes, I had create a PR https://github.com/tweag/HaskellR/pull/263. Please check it.

**Comment by GregorySchwartz** [comment]
I am getting this error when building a library on macOS which depends on `inline-r`, failing at the module that mostly using `R`. Is there an equivalent to `-fno-ghci-sandbox` without ghci?

**Comment by qnikst** [comment]
The closest equivalent is to run event loop and R evaluations in the main thread (`Thread1`). You can achieve that by making something like:
```
forever $ join $ atomically $ readTQueue input
```
And all other threads will send computations to that `input` Queue. 
It looks rather pessimistic from the performance view point, so other possibilities are to run `forkOn 0` and pass a flag that binds HECs to the OS threads.

If you have a minimal example can you share that one, I have a system where I can test and fix the issue now.

**Comment by GregorySchwartz** [comment]
I should mention that it's when compiling a program, not running.

**Comment by qnikst** [comment]
Oh.. that's pretty bad. I'll think what can we do around that.

**Comment by mboes** [comment]
@qnikst 
> Oh.. that's pretty bad. I'll think what can we do around that.

Anything we could possibly do? I'm stumped.

**Comment by GregorySchwartz** [comment]
What could be causes this issue when building (with Nix) on macOS only?

**Comment by GregorySchwartz** [comment]
Exact location:

```
Preprocessing library for differential-0.1.2.1..
Building library for differential-0.1.2.1..
[1 of 5] Compiling Types            ( src/Types.hs, dist/build/Types.o )
[2 of 5] Compiling Plot             ( src/Plot.hs, dist/build/Plot.o )
Error: C stack usage  17587453424728 is too close to the limit
Error: C stack usage  17587453424776 is too close to the limit
Error: C stack usage  17587453424312 is too close to the limit
Fatal error: unable to initialize the JIT
```

**Comment by facundominguez** [comment]
If it is only used for parsing/lexing, perhaps it would be simpler to run R as a separate process during compilation.

**Comment by qnikst** [comment]
I was thinking about running our code in separate process, but using R directly may actually work.
