### ISSUE TITLE
Can't use library() to load package in r QQ on OS X.

### ISSUE THREAD

**Issue by JulianZhang** [tweag/HaskellR#267]
I was use notebook on mac OS X, I find that if I run [r|libary(xxx)|] the kernel will dead.

And then I try to use H in command line, If I use wrong package name it will give me a runtime error, when I use right package name will get "Segmentation fault: 11".

$stack  exec H
Prelude H.Prelude> [r|1+1|]
0x00007ff3c448aa08
Prelude H.Prelude> [r|library('MSBVAR1')|]
*** Exception: R Runtime Error: Error in library("MSBVAR1") : there is no package called ‘MSBVAR1’

Prelude H.Prelude> [r|library('MSBVAR')|]
Segmentation fault: 11
$

**Comment by mboes** [comment]
Likely the second segfault came from the fact that there was a runtime error before that. If so that would be a bug in inline-r. But in the meantime a workaround here should be to restart H before loading with the correct library name.
