### ISSUE TITLE
Potentially conflicting ghc in stack.yaml and shell.nix

### ISSUE THREAD

**Issue by alexvorobiev** [tweag/HaskellR#269]
`stack.yaml` requests `resolver: lts-6.12` which assumes `ghc-7.10.3` but `shell.nix` has `inherit ghc;` which can resolve to any version of ghc potentially. Should it be set to `haskell.packages.ghc7103.ghc` instead?

**Comment by mboes** [comment]
I believe this is as intended: `inherit ghc;` means Stack gets to choose which GHC version to use when using the `--nix` flag (just as it does when not using the `--nix` flag). By default, it'll select the GHC version for LTS 6.12. But if you override the resolver say by passing `--resolver nightly` on the command-line, then Stack will tell Nix to provision some other version of GHC.

**Comment by alexvorobiev** [comment]
The main reason I asked was I was getting an error when I tried to run `stack build --nix` about missing `ghc` attribute so I had to edit `shell.nix`. After I commented the `inherit ghc;` line and added
```
ghc = haskell.packages.ghc7103.ghc;
```
the build worked. So it looks like the default behavior you described (which is what I expected as well) doesn't work.

**Comment by mboes** [comment]
Ok yes, that's an upstream issue. Stack >= 1.2 highly recommended if you're going to use `--nix`.
