### ISSUE TITLE
Feature request: calling Haskell from R

### ISSUE THREAD

**Issue by alexvorobiev** [tweag/HaskellR#274]
In our workflow analysts write many R functions. If performance becomes a bottleneck we often use Rcpp (http://dirk.eddelbuettel.com/code/rcpp.html) to rewrite the functions in c++ keeping the user-visible R API intact. Would it be possible to adapt inline-r to that use case?

**Comment by mboes** [comment]
Sure! A user attempted this already:
http://stla.github.io/stlapblog/posts/FloatExpansionHaskell.html

We could include this in the HaskellR guide.

**Comment by alexvorobiev** [comment]
Thanks for the example! Are you considering making the integration more seamless like [sourceCpp](https://www.rdocumentation.org/packages/Rcpp/versions/0.12.6/topics/sourceCpp) or [Rcpp attributes](https://cran.rstudio.com/web/packages/Rcpp/vignettes/Rcpp-attributes.pdf)?

**Comment by michelk** [comment]
The [rustr](https://github.com/rustr/rustr) and [rustinr](https://github.com/rustr/rustinr) packges could serve as inspiration for a more seamless approach.

**Comment by stla** [comment]
> Sure! A user attempted this already:
> http://stla.github.io/stlapblog/posts/FloatExpansionHaskell.html

Hi. FYI, I rewrote this article here: <https://laustep.github.io/stlahblog/posts/FloatExpansionHaskell.html>

Also see this one, something more elaborate: <https://laustep.github.io/stlahblog/posts/YoungTableaux.html>

And this package where I use for the first time the function `indexVector` in the Haskell code which generates the DLL: <https://github.com/stla/skewtableaux>

**Comment by idontgetoutmuch** [comment]
Also calling Haskell from C https://idontgetoutmuch.wordpress.com/2017/01/14/calling-haskell-from-c/ and of course you can call C from R.

**Comment by idontgetoutmuch** [comment]
I really think this is out of scope for inline-r - I suggest we close this issue.
