### ISSUE TITLE
It's impossible to interrupt execution of R code by haskell exception

### ISSUE THREAD

**Issue by Shimuuar** [tweag/HaskellR#278]
Bug is demonstrated by following simple program. R code enters infinite loop and exceptions to the thread which is running code will not be delivered until R code finishes.

```haskell
{-# LANGUAGE QuasiQuotes #-}
import Control.Monad
import Control.Concurrent
import System.Exit

import qualified Language.R.Instance as R
import qualified Foreign.R           as R
import           Language.R.QQ

main = R.withEmbeddedR R.defaultConfig $ do
  tid <- myThreadId
  forkIO $ do
    threadDelay (1000*1000)
    putStrLn stderr "KILLIN"
    throwTo tid ExitSuccess
  R.runRegion  $ void
    [r|
      print(summary(1:10));
      while(1){};
    |]
  return ()

```

**Comment by qnikst** [comment]
It seems that the only way to stop try eval is to send `sigINT` to the process that called `eval`. But ghc RTS sets it's own signal handler. I'll try to find and propose way forward here.

**Comment by qnikst** [comment]
I've played a bit more with the code above. The problem was that by default inline-r doesn't allow R to set it's own signal handlers, this can be changed by configuring start parameters:
`defaultConfig{signalHandlers=Last (Just True)}`  then R will set it's own signal handlers, interesting ones are:
  * SIGINT -  stop current execution
  * SIGUSR1 - stop R execution, store enviromenent and exit
  * SIGUSR2 - stop R execution and exit

Problems:
   Haskell also uses SIGINT - for graceful exit with dumping of all profiling information and stats, SIGUSR2 - for printing stack trace to stderr (>8.0 + libwd support), and I see no sane way to restore haskell signal handlers if needed.

Full program that work for me:
```
import System.Exit
import System.IO
import System.Posix.Signals

import qualified Language.R.Instance as R
import qualified Foreign.R           as R
import           Language.R.QQ
import Data.Monoid

import Control.Exception

main = R.withEmbeddedR R.defaultConfig{R.configSignalHandlers=Last (Just True)} $ do
  tid <- myThreadId
  forkIO $ do
    threadDelay (1000*1000)
    hPutStrLn stderr "KILLIN"
    raiseSignal sigINT
    -- throwTo tid ExitSuccess
    -- R.runRegion $ void $ [r| stop("crazy"); |] -- doesn't work
  e <- trySome $ R.runRegion  $ void
    [r|
      print(summary(1:10));
      while(1){};
    |]
  print e
  putStrLn "we are fine!"

trySome :: IO a -> IO (Either SomeException a)
trySome = try
```

I think this ticket could be closed once we could have best of all words - stop R execution and gracefully stop haskell runtime.

**Comment by qnikst** [comment]
One solution is to move haskell termination logic to sigterm:
```haskell
main = do
  original <- installHandler sigINT (Catch $ return ()) Nothing
  installHandler sigTERM original Nothing
```
without fix:
```
qnikst@qwork ~/workspace/tweag/haskellR/t $ ./1 +RTS -s
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   1.00    3.25    5.50    5.50    7.75   10.00
KILLIN

Left R Runtime Error:
we are fine!
Terminated
```
with fix:
```
./1 +RTS -s
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   1.00    3.25    5.50    5.50    7.75   10.00
KILLIN

Left R Runtime Error:
we are fine!
         155,456 bytes allocated in the heap
          32,672 bytes copied during GC
          92,968 bytes maximum residency (2 sample(s))
          21,720 bytes maximum slop
               1 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0         0 colls,     0 par    0.000s   0.000s     0.0000s    0.0000s
  Gen  1         2 colls,     0 par    0.000s   0.000s     0.0002s    0.0002s

  TASKS: 5 (1 bound, 4 peak workers (4 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.001s  (  0.001s elapsed)
  MUT     time    1.199s  (  1.200s elapsed)
  GC      time    0.000s  (  0.000s elapsed)
  EXIT    time    0.001s  (  0.000s elapsed)
  Total   time    1.206s  (  1.202s elapsed)

  Alloc rate    129,673 bytes per MUT second

  Productivity  99.9% of total user, 100.2% of total elapsed

gc_alloc_block_sync: 0
whitehole_spin: 0
gen[0].sync: 0
gen[1].sync: 0
```

**Comment by Shimuuar** [comment]
There's question of documentation as well. Description of `configSignalHandlers` says:

>    Set to True if you're happy to let R install its own signal handlers during initialization.

but doesn't mention what these handlers do or where to look up this info.

**Comment by qnikst** [comment]
Documentation added in https://github.com/tweag/HaskellR/pull/280

**Comment by Shimuuar** [comment]
Thank you!

**Comment by Shimuuar** [comment]
It turns out that R uses flag `R_interrupts_pending` for interrupting computation. So interrupting code is as simple as setting this flag to 1 from another thread. There's of course possible problems due to concurrent access but I suspect that R signal handler is likely to be called from another thread so it's not better.
