### ISSUE TITLE
Factors result in SIGSEGV.

### ISSUE THREAD

**Issue by GregorySchwartz** [tweag/HaskellR#284]
I would assume that a factor would be treated as a String for straightforward behavior in Haskell. At the very least, there should be at least an error in R about type mismatches. Even better, an error during compilation for mismatches. However, I would not expect this:

```
stack exec H
Prelude H.Prelude> f :: String -> R s String; f x = return . take 2 $ x
Prelude H.Prelude> p [r| f_hs("hello") |]
[1] "he"
Prelude H.Prelude> p [r| f_hs(factor("hello")) |]
fish: Job 1, “stack exec H” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by qnikst** [comment]
Factor is not a strict, it's an int + information attached in args. So segfault is expected, but what is not expected that dymanic check didn't happen here.
I'll check the reason for that and provide a safe code that will allow you to work with factors and other complex objects.

**Comment by mboes** [comment]
Well, to be clear, segfaults are never the right behaviour.

This bug may in fact be a bug where none of the function arguments are checked for some reason. @qnikst are you looking into it?

**Comment by qnikst** [comment]
PR #285 should fix the segfault, factors are still not usable with current API.
This will be solved with R value parser that I'll prepare soon.

**Comment by qnikst** [comment]
With new parser see #289 it's possible to do better things:
```
ikst@nixos:~/workspace/tweag/HaskellR]$ stack exec H --stack-yaml=stack-ghc-8.0.yaml 
Prelude H.Prelude> x <- [r| factor("hello") |]        
Prelude H.Prelude> :m +Language.R.Parser     
Prelude H.Prelude Language.R.Parser> Right t <- parseOnly (getS3Class) x
Prelude H.Prelude Language.R.Parser> t
["factor"]
Prelude H.Prelude Language.R.Parser> Right t <- parseOnly (charList <$> attribute SString "levels") x                
Prelude H.Prelude Language.R.Parser> t
["hello"]
```

This allow to get any information from the SEXP value. Currently this feature was testing in another project, but it's still experimental in upstream. Soon it will be merged and more helpers will come with it, that will allow to parse matrixes, arrays, factors.
