### ISSUE TITLE
How to use non-base libraries with IHaskell/Jupyter

### ISSUE THREAD

**Issue by skeydan** [tweag/HaskellR#293]
Hi,
sorry it's me again, this time it's a super stupid question I'm sure, but how can use e.g. Text.CSV in Jupyter notebook?
I start Jupyter like this (from some project directory)

stack --stack-yaml=/home/key/code/haskell/HaskellR/stack.yaml --nix exec jupyter notebook

but then, how/where can I tell stack which libraries I'll need in my notebook?

Sorry for asking such a basic question ...
Thanks,
Sigrid

**Comment by Fuuzetsu** [comment]
I don't have time to check right this second but perhaps try

```
stack --stack-yaml=/home/key/code/haskell/HaskellR/stack.yaml --nix --package csv exec -- jupyter notebook
```

That is, `stack exec` takes `--package` flag.

**Comment by skeydan** [comment]
Hi, thanks for the quick answer, but stack doesn't take a package argument...

[key@key haskellR_intro]$ stack --stack-yaml=/home/key/code/haskell/HaskellR/stack.yaml --nix --package csv exec -- jupyter notebook
Invalid option `--package'

**Comment by Fuuzetsu** [comment]
oops, try this way instead

```
stack --stack-yaml=/home/key/code/haskell/HaskellR/stack.yaml --nix exec --package csv -- jupyter notebook
```

The argument should have been to `exec`, not to `stack`

**Comment by skeydan** [comment]
Wonderful, thank you so much!!!
