### ISSUE TITLE
cannot install inline-r 0.9.0.2 on Windows

### ISSUE THREAD

**Issue by stla** [tweag/HaskellR#306]
Hello, 

 The installation of `inline-r 0.9.0.2` (resolver `nightly-2017-12-09`) fails on my computer, Windows 7.
```
Configuring inline-r-0.9.0.2...
Preprocessing library for inline-r-0.9.0.2..
C:\path\to\stack\x86_64-windows\ghc-8.2.2\bin\hsc2hs.exe: createProcess: does not exist (No such file or directory)
```

**Comment by mboes** [comment]
That's odd. On Appveyor this build proceeds much further than that: https://ci.appveyor.com/project/mboes/haskellr/build/220. Have you tried using the latest LTS, instead of Nightly?

**Comment by stla** [comment]
No, but it works with `nightly-2017-12-13` (ghc 8.2.2).
