### ISSUE TITLE
Move away from c2hs

### ISSUE THREAD

**Issue by mboes** [tweag/HaskellR#307]
c2hs has caused us all manner of problems in the past. But now we're running into this:

https://github.com/haskell/c2hs/issues/192

Until this issue is fixed, Nix users cannot use HaskellR. Nor can users of distros with GCC 7 or glibc >= 2.26. It's just another example of unnecessary complications we get from using c2hs. So let's get rid of it. It's the best way to insulate ourselves from similar problems in the future. There is a better alternative now: inline-c.

**Comment by qnikst** [comment]
PR in #308

**Comment by nmattia** [comment]
@qnikst looks like this was fixed in #309 ?
