### ISSUE TITLE
c2hs problem prevents stack build  >>> Syntax error !       The symbol `__value' does not fit here.

### ISSUE THREAD

**Issue by OscarSouth** [tweag/HaskellR#310]
I've seen this referenced in a number of places but not yet seen any reference to how to solve the problem.  Have scoured the available issues relating to this for possible solutions!

Is there any update how to work around this?  I'm trying to build H via stack.

oscarsouth@OS-LAPTOP:~$ stack build --copy-bins H
inline-r-0.9.0.1: configure
inline-r-0.9.0.1: build
Progress: 1/2
--  While building custom Setup.hs for package inline-r-0.9.0.1 using:
      /home/oscarsouth/.stack/setup-exe-cache/x86_64-linux-nopie/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/oscarsouth/.stack/global-project/.stack-work/logs/inline-r-0.9.0.1.log

    Configuring inline-r-0.9.0.1...
    Building inline-r-0.9.0.1...
    Preprocessing library inline-r-0.9.0.1...
    c2hs: C header contains errors:
    
    /usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h:21: (column 40) [ERROR]  >>> Syntax error !
      The symbol `__value' does not fit here.

Thanks,
Oscar

**Comment by mboes** [comment]
This is probably due to a too recent glibc, that c2hs doesn't support. This is why we've removed use of c2hs in the master branch. See #307 .

**Comment by OscarSouth** [comment]
Ah thanks, good to see that this is being eliminated.

Is there a solution to installing this with newer code, or would a more direct (if blunt) solution be to downgrade glibc?  I do indeed have version 2.26 presently.

My current Ubuntu installation is only going to live for another few months so I don’t mind a bit of a messy short term solution.  I read through everything I can find on this issue and couldn’t discern if there’s a solution (tried quite a few things) or if it’s currently an ongoing discussion of a currently unavoidable problem.

Apologies if I’m asking questions a little nievely by the way, I made a career jump from music performance into computing last year and I’m still deepening my familiarity with some of the technologies and pathways involved!

Thanks,
Oscar

**Comment by qnikst** [comment]
Hello Oscar.

Sorry for the late response, but in general the best way forward is to either add master revision to stack.yaml file (or checkout package if you use cabal.project). Downgrading glibc is not best way forward.

stack based solution add in stack yaml:

```
packages:
- location:
    git: https://github.com/tweag/HaskellR.git
    commit: 5b18d994046971f99540df2dc8c962391f553bbf
  subdirs:
    - inline-r
```

`cabal.project` based solution, add following line
```
optional-packages: extra/**/*.cabal
```
and checkout inline-r into the extra directory.


Hope it will work for you. And we are going to release new version of the inline-r ASAP that version should have fix included.

**Comment by mboes** [comment]
I think we can be more helpful still to @OscarSouth by cutting a new point release. @qnikst could you do that?

**Comment by OscarSouth** [comment]
Thanks very much for the info and assistance.  I'll see if I can get it working this evening.

**Comment by OscarSouth** [comment]
Thanks again for the help.  Adding "extra-deps: - inline-r-0.9.1" to stack.yaml then re-running "stack build --copy-bins H" allowed that command to run successfully and so solved the issue that this topic was created about.

HaskellR now runs perfectly using "stack exec H", however I was still not yet able to run it in an iHaskell notebook.

I was starting to run through the cells in the demonstration notebook here:
https://github.com/tweag/HaskellR/blob/master/IHaskell/examples/tutorial-ihaskell-inline-r.ipynb

When the second cell (of that test notebook) is run, the iHaskell kernel crashes completely.  You can see what is happening here:
![image](https://user-images.githubusercontent.com/32574713/35476066-9eb902b2-03a1-11e8-8ff1-0161b3c3b80f.png)

I believe that this may be connected with iHaskell rather than HaskellR, but I'm just including the info here in case it's anything that you recognise. 

I also attempted a reinstall according to the insight here:
https://github.com/gibiansky/IHaskell/issues/698

There was no change to the result though.

Thanks again for helping me to solve the original issue and for pushing a point release.  I'll explore the install process more in the future and hopefully sort this.  As an R user who is really enjoying exploring and becoming increasingly familiar with the Haskell language, what you've built is really something wonderful.  I'm looking forward to using it a a great deal in the future!

**Comment by mboes** [comment]
Hm. It took a while for IHaskell to get GHC-8 support, but now that it's there, it's possible that additional linker flags are necessary for inline-r to work properly with it. Could you file a separate issue? That way we can close this one.

Great to hear about HaskellR being useful to you. :)

**Comment by OscarSouth** [comment]
I’ll post a new issue later today.  Feel free to close this!
