### ISSUE TITLE
Unable to initialize R in tutorial-ihaskell-inline-r notebook

### ISSUE THREAD

**Issue by nickoralias** [tweag/HaskellR#316]
I followed the directions at https://tweag.github.io/HaskellR/docs/build-and-install.html and installed everything using stack's nix integration on macOS High Sierra (10.13.2).  I had no trouble installing and using H, but when I try to run the following cell in the tutorial-ihaskell-inline-r notebook my kernel crashes every time:

import qualified H.Prelude as H
H.initialize H.defaultConfig

For this reason I'm unable to use inline-r in IHaskell.  The following happens each time I try running the above code:

[I 09:35:18.793 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel b937eb83-70d0-4ac0-8515-46358611a370 restarted

**Comment by teuffy** [comment]
Same  issue 
running ﻿stack --nix exec jupyter notebook -- --port=8889

and getting this error from the console
[I 02:17:32.364 NotebookApp] Adapting to protocol v5.0 for kernel 4a10897d-d059-4591-a94f-ad80221d7d6f
Error: C stack usage  17587460330208 is too close to the limit
Error: C stack usage  17587460330256 is too close to the limit
Error: C stack usage  17587460330160 is too close to the limit
Fatal error: unable to initialize the JIT

**Comment by qnikst** [comment]
Thanks for reporting the issue.

Have you tried to add `:set -fno-ghci-sandbox` to `~/.ihaskell/rc.hs` like described on FAQ page [1]?

> If you get this error in a Jupyter notebook, you can add :set -fno-ghci-sandbox to ~/.ihaskell/rc.hs. If the file didn’t exist previously just create it.

[1] https://tweag.github.io/HaskellR/docs/faq.html
