### ISSUE TITLE
dyld: Library not loaded: libR.dylib

### ISSUE THREAD

**Issue by homam** [tweag/HaskellR#318]
I have this error in macOS while running `stack --nix build`

```
--  While building custom Setup.hs for package inline-r-0.9.1 using:
      /Users/homam/.stack/setup-exe-cache/x86_64-osx-nix/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-osx-nix/Cabal-2.0.1.0 build lib:inline-r --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/homam/dev/haskell/HaskellR/.stack-work/logs/inline-r-0.9.1.log

    Configuring inline-r-0.9.1...
    Preprocessing library for inline-r-0.9.1..
    dyld: Library not loaded: libR.dylib
      Referenced from: /Users/homam/dev/haskell/HaskellR/inline-r/.stack-work/dist/x86_64-osx-nix/Cabal-2.0.1.0/build/Foreign/R/Embedded_hsc_make
      Reason: image not found
    running .stack-work/dist/x86_64-osx-nix/Cabal-2.0.1.0/build/Foreign/R/Embedded_hsc_make failed (exit code -6)
    command was: .stack-work/dist/x86_64-osx-nix/Cabal-2.0.1.0/build/Foreign/R/Embedded_hsc_make  >.stack-work/dist/x86_64-osx-nix/Cabal-2.0.1.0/build/Foreign/R/Embedded.hs
```

I get the same error both on `master` and `v0.9.1`

```
➜  HaskellR git:(master) stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

```
➜  HaskellR git:(master) nix-shell --version
nix-shell (Nix) 1.11.16
```

**Comment by idontgetoutmuch** [comment]
I am on MACos and run with this shell.nix

```{ nixpkgs ? import <nixpkgs> {}, compiler ? "ghc822", doBenchmark ? false }:

let

  inherit (nixpkgs) pkgs;

f = { mkDerivation, base, inline-r, integration, R, random, stdenv
    , template-haskell, temporary }:
mkDerivation {
  pname = "mrp";
  version = "1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    base
    inline-r
    integration
    random
    template-haskell
    temporary ];
  executableSystemDepends = [
    R
    pkgs.rPackages.ggplot2
    pkgs.rPackages.maptools
    pkgs.rPackages.reshape2
    pkgs.rPackages.rgeos
    pkgs.rPackages.rgdal
    pkgs.rPackages.rstan ];
  license = stdenv.lib.licenses.bsd3;
};

  haskellPackages = if compiler == "default"
                       then pkgs.haskellPackages
                       else pkgs.haskell.packages.${compiler};

  variant = if doBenchmark then pkgs.haskell.lib.doBenchmark else pkgs.lib.id;

  drv = variant (haskellPackages.callPackage f {});

in

  if pkgs.lib.inNixShell then drv.env else drv
```

**Comment by homam** [comment]
My whole system stops responding and crashes by running `stack --nix build` after I changed my `shell.nix` to the above.

**Comment by mboes** [comment]
`stack --nix` is currently unsupported for this project on macOS. See the installation instructions for how to use `brew` instead. That said, could you try the following change?

```
-  LD_LIBRARY_PATH = ["${R}/lib/R/"];
+  DYLD_LIBRARY_PATH = ["${R}/lib/R/"];
```

It *might* work.

**Comment by idontgetoutmuch** [comment]
What I meant was to do something like

```
nix-shell shell.nix -I nixpkgs=https://github.com/nixos/nixpkgs/archive/6a6bdca507e8445b2efd8f73ab86f9660f9bc3c2.tar.gz 2> log.txt
```

and then in the nix shell you can fire up ghci and load something like this

```
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ScopedTypeVariables #-}

import qualified Language.R as R
import Language.R (R)
import Language.R.QQ
import Data.Int

myTest :: R s [Double]
myTest = R.dynSEXP <$> [r| airquality$Ozone |]

myTestA :: R s [Int32]
myTestA = R.dynSEXP <$> [r| melt(airquality)$variable |]

main = R.withEmbeddedR R.defaultConfig $ do
  r <- R.runRegion $ do _ <- [r| library(reshape2) |]
                        myTestA
  print r
```

Notes:

- You may need to turn off the tests for inline-r - I forgot how I did this but it's somewhere in here https://github.com/Gabriel439/haskell-nix (probably an overlay)
- Using such a recent nixpkgs will almost certainly actually build R (not just download it)
- You don't have to do any install.packages (even rgdal is done for you)

I keep meaning to write this workflow up as a blog.

**Comment by homam** [comment]
I have this error when I run `nix-shell shell.nix`: `error: attribute ‘ghc’ missing, at ./shell.nix:1:37`.

`DYLD_LIBRARY_PATH = ["${R}/lib/R/"];` also didn't work, I still have the same error.

**Comment by idontgetoutmuch** [comment]
If you ran this exact command

```
nix-shell shell.nix -I nixpkgs=https://github.com/nixos/nixpkgs/archive/6a6bdca507e8445b2efd8f73ab86f9660f9bc3c2.tar.gz 2> log.txt
```

and got that error then that's beyond my nix skills. You could try asking the nix folks.

Alternatively you can try the homebrew route.

**Comment by mboes** [comment]
It turns out that on macOS R puts its library in a slightly different path. So the `DYLD_LIBRARY_PATH` line should read:

```
DYLD_LIBRARY_PATH = ["${R}/lib/R/lib"];
```

See #319 for the full `shell.nix` that we now also check in CI.

**Comment by homam** [comment]
OK thanks everyone, finally this worked for me:

* Installed [brew packages](https://tweag.github.io/HaskellR/docs/build-and-install.html)
* https://github.com/tweag/HaskellR/issues/200#issuecomment-143566822
* Applied https://github.com/tweag/HaskellR/pull/319

**Comment by homam** [comment]
_I might need to open up a new issue for this_

Running this line `H.initialize  H.defaultConfig` from [tutorial-ihaskell-inline-r.ipynb](http://localhost:8888/notebooks/IHaskell/examples/tutorial-ihaskell-inline-r.ipynb) crashes the kernel

I know that `H` loads, I can inspect `:t H.defaultConfig`.

This is the relevant lines in my terminal after running `stack exec jupyter notebook`

```
...
[I 13:09:55.587 NotebookApp] Adapting to protocol v5.0 for kernel c7f5e9df-fbef-48f6-9077-ca4dd5af289b
Error: C stack usage  17587414160200 is too close to the limit
Error: C stack usage  17587414160248 is too close to the limit
Error: C stack usage  17587414160168 is too close to the limit
Fatal error: unable to initialize the JIT

[I 13:10:05.334 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel c7f5e9df-fbef-48f6-9077-ca4dd5af289b restarted
[I 13:11:56.626 NotebookApp] Saving file at /IHaskell/examples/tutorial-ihaskell-inline-r.ipynb
```

**Comment by mboes** [comment]
@homam please do! I noticed the same error you did when running tests on macOS. That's why tests are at the moment disabled in macOS CI. They run fine in Linux though. @qnikst is investigating.
