### ISSUE TITLE
im trying to get haskellR to have in emacs 

### ISSUE THREAD

**Issue by HelioJimeArch** [tweag/HaskellR#335]
but i get this output 
hese paths will be fetched (85.41 MiB download, 206.42 MiB unpacked):
  /nix/store/19aayskcfdnyi0f5f3lg9ljlv2yhzw6z-R-3.4.3
  /nix/store/347h96g34wg35l2kv8fbn73i4m40gzdc-openjdk-8u152b16
  /nix/store/nlxfl78fzm025xdhwyk3j03kjikm78p7-tk-8.6.6-dev
  /nix/store/pn6qjkk7z37nhfnljbi2y84335zh82cc-openjdk-8u152b16-jre
copying path '/nix/store/pn6qjkk7z37nhfnljbi2y84335zh82cc-openjdk-8u152b16-jre' from 'https://cache.nixos.org'...
preallocating file of 15044816 bytes: No space left on device
copying path '/nix/store/nlxfl78fzm025xdhwyk3j03kjikm78p7-tk-8.6.6-dev' from 'https://cache.nixos.org'...
error: build of '/nix/store/wawaxw108cm4hlx8bvcfd0gxa5jbxl15-R-3.4.3.drv' failed 

what can i do ?

**Comment by qnikst** [comment]
Hello, @HelioJimeArch. It seems that you have no space on your device left
> preallocating file of 15044816 bytes: No space left on device

you may free up some space by calling nix-collect-garbage or by removing some no longer needed files.

Hope that helps.

**Comment by HelioJimeArch** [comment]
ok , bun then i get this output  
    [1 of 1] Compiling Main             ( nls2/Main.hs, .stack-work/dist/x86_64-linux-nix/Cabal-2.0.1.0/build/nls2/nls2-tmp/Main.o )
    Linking .stack-work/dist/x86_64-linux-nix/Cabal-2.0.1.0/build/nls2/nls2 ...
    Preprocessing executable 'fib' for HaskellR-examples-0.1.0.0..
    Building executable 'fib' for HaskellR-examples-0.1.0.0..
    [1 of 2] Compiling Fib              ( fib/Fib.hs, .stack-work/dist/x86_64-linux-nix/Cabal-2.0.1.0/build/fib/fib-tmp/Fib.o )
    Language.R.Interpreter: Cannot increase stack size limit.Try increasing your stack size limit manually:$ ulimit -s unlimited

    /mnt/d/LinuxApps/HaskellR/examples/fib/Fib.hs:23:54: error:
        • Exception when trying to run compile-time code:
            setResourceLimit: invalid argument (Invalid argument)
          Code: template-haskell-2.12.0.0:Language.Haskell.TH.Quote.quoteExp
                  r " n_hs "
        • In the quasi-quotation: [r| n_hs |]
       |
    23 | neg (fromSEXP -> R.TRUE)  (fromSEXP -> n :: Int32) = [r| n_hs |]
       |                                                      ^^^^^^^^^^^

**Comment by HelioJimeArch** [comment]
im trying to get rid of things

**Comment by HelioJimeArch** [comment]
$ ulimit -s unlimited
bash: ulimit: stack size: cannot modify limit: Invalid argument

**Comment by qnikst** [comment]
WSL may miss some required features, I have such a system around and will try to test inline-r installation there.

**Comment by mboes** [comment]
Closing since the original issue was resolved. But the WSL limits thing sounds like an interesting one to crack. Could you file a separate report about that?
