### ISSUE TITLE
CentOS 7: The pkg-config package 'libR' version >=3.0 is required but it could not be found.

### ISSUE THREAD

**Issue by rsolano1-uw** [tweag/HaskellR#348]
Hello,
I am trying to build the [too-many-cells](https://github.com/GregorySchwartz/too-many-cells) project, which pulls inline-r-0.9.2 as a dependency. I have cloned the git repo and run `stack build` to build the project.
When stack gets to trying to install inline-r, it fails with the error:
```
inline-r      > configure
inline-r      > Configuring inline-r-0.9.2...
inline-r      > Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3: The pkg-config package 'libR' version
inline-r      > >=3.0 is required but it could not be found.
inline-r      > 
```
I have R 3.6.1 installed on my system in a custom location that is loaded into my $PATH and $LD_LIBRARY_PATH. This installation has both `libR.so` and `libR.pc`. The contents of `libR.pc` point to the directory that contains `libR.so`

I get this same error when I run `stack build --extra-include-dirs=$rbin --extra-include-dirs=$rpkg --extra-include-dirs=$rlib --extra-lib-dirs=$rbin --extra-lib-dirs=$rpkg --extra-lib-dirs=$rlib`, where `$rbin` is `$rbase/bin`, `$rlib` is `$rbase/lib64/R/lib`, and `$rpkg` is `$rbase/lib64/pkgconfig`. The `$rpkg` directory contains my `libR.pc` file and the `$rlib` directory contains my `libR.so` file.

Any help would be greatly appreciated.

**Comment by qnikst** [comment]
Hello, can you check if libR.pc is in one of `PKG_CONFIG_PATH` if not then add the path where it's located to the colon separated PKG_CONFIG_PATH environment variable, I hope it should help.
