### ISSUE TITLE
Request version bump and hackage push

### ISSUE THREAD

**Issue by Xitian9** [tweag/HaskellR#361]
**Is your feature request related to a problem? Please describe.**
Inline-r no longer compiles in nixpkgs-unstable. e5eccb414e9cf80cc4971edb423b9fb014b82380 fixes this problem, but has not been put on hackage yet.

**Describe the solution you'd like**
Make a minor release for current master and push it to hackage.

**Comment by mboes** [comment]
New release last week: http://hackage.haskell.org/package/inline-r.

Also re-adding to Stackage: https://github.com/commercialhaskell/stackage/pull/5793.
