### ISSUE TITLE
Cannot build on Debian

### ISSUE THREAD

**Issue by erikd** [tweag/HaskellR#376]
**Describe the bug**
The `inline-r.cabal` file contains:
```
     pkgconfig-depends: libR
```
but on Debian the `libr` pkg-config file is called `r3.pc`.

**To Reproduce**
On Debian
```
git clone https://github.com/tweag/HaskellR/
cd HaskellR
cabal build inline-r
```
**Expected behavior**
I expect it to build.

**Environment**
 - Debian Linux (testing)
 - Version of the code: commit c3ba1023480e26ade420896bcb629ceaad59f308

**Additional context**

**Comment by erikd** [comment]
Turns out I was installing the wrong version of `R`. On Debian the package required is `r-base`, `r-base-dev` and `r-core`.

**Comment by facundominguez** [comment]
Thanks @erikd. Do you think it would be helpful to mention those packages in the readme?
