### ISSUE TITLE
inline-r's test suite does not accept most recent version of strict (0.5)

### ISSUE THREAD

**Issue by ysangkok** [tweag/HaskellR#411]
Strict-0.5 is only release compatible with assoc-1.1, which is needed to work with bifunctors 5.6.1 (but not 5.6), which is the only release series working with semigroupoids 6, which is the only series that works on GHC 9.6.

**Comment by ConnorBaker** [comment]
@ysangkok I bumped several of the upper bounds in https://github.com/tweag/HaskellR/commit/3cb01da0902ef705d2bd40874fe53333f4949b2f -- would you let me know if that fixes your issue? I'm getting a linker error when building, but I suspect that's an issue with the beta release of Fedora I'm using.

**Comment by ysangkok** [comment]
@ConnorBaker It does fix all the bounds issues, but there is an import adjustment that needs to be made, I have submitted #414 to correct this issue.
